function sim = setupBinauralSimulator()
%setupBinauralSimulator starts the Binaural SImulator and applies all common
%                       settings, like position of listener and length of
%                       simulation
%
%   USAGE
%       sim = setupBinauralSimulator()
%
%   OUTPUT PARAMETERS
%       sim  - Binaural Simulator object

% NOTE: the actual BRS (impulse responses) data set and the audio material
% will be set in the respective functions

sim = simulator.SimulatorConvexRoom();
set(sim, ...
    'BlockSize',            4096, ...
    'SampleRate',           44100, ...
    'NumberOfThreads',      1, ...
    'LengthOfSimulation',   5, ...
    'Renderer',             @ssr_brs, ...
    'Verbose',              false, ...
    'Sources',              {   simulator.source.Point(), ...
                                simulator.source.Point(), ...
                                simulator.source.Point()}, ...
    'Sinks',                simulator.AudioSink(2) ...
    );
set(sim.Sinks, ...
    'Name',                 'Head', ...
    'Position',             [0.00  0.00  0.00]' ...
    );

set( sim.Sources{1}, 'AudioBuffer', simulator.buffer.Ring(1) );
sim.Sources{1}.AudioBuffer.loadFile( ...
    'sound_databases/generalSoundsNI/alarm/Alarm+8001_04.wav', sim.SampleRate);
sim.Sources{1}.IRDataset = simulator.DirectionalIR( ...
    'impulse_responses/qu_kemar_rooms/auditorium3/QU_KEMAR_Auditorium3_src4_xs+0.00_ys+1.50.sofa' );

set( sim.Sources{2}, 'AudioBuffer', simulator.buffer.Ring(1) );
sim.Sources{2}.AudioBuffer.loadFile( ...
    'sound_databases/generalSoundsNI/piano/MusicPiano_DIGIB04-63.wav', sim.SampleRate);
sim.Sources{2}.IRDataset = simulator.DirectionalIR( ...
    'impulse_responses/qu_kemar_rooms/auditorium3/QU_KEMAR_Auditorium3_src5_xs-0.75_ys+1.30.sofa' );

set( sim.Sources{3}, 'AudioBuffer', simulator.buffer.Ring(1) );
sim.Sources{3}.AudioBuffer.loadFile( ...
    'sound_databases/generalSoundsNI/engine/MachineSciFi+8006_94_1.wav', sim.SampleRate);
sim.Sources{3}.IRDataset = simulator.DirectionalIR( ...
    'impulse_responses/qu_kemar_rooms/auditorium3/QU_KEMAR_Auditorium3_src6_xs+0.75_ys+1.30.sofa' );

sim.rotateHead(90, 'absolute');
sim.Init = true;